version: "3.8"
services:
  postgres:
    image: "postgres:16.3-bullseye"
    container_name: "postgres"
    restart: "unless-stopped"
    env_file: ".env"
    volumes:
      - "postgres_volume:/var/lib/postgresql/data"


  redis:
    image: "redis:7.2.5"
    container_name: "redis"
    restart: "unless-stopped"
    volumes:
      - "redis_volume:/data"
    command: "redis-server --save 600 1 --loglevel warning"


  llm_bot:
    image: "uralnuthatch/llm_bot:latest"
    container_name: "llm_bot"
    restart: "unless-stopped"
    volumes:
      - "./.env:/LLM_bot/.env"
    depends_on:
      - "postgres"
      - "redis"


volumes:
  postgres_volume:
  redis_volume: